# config/modules.toml

[mux]
description = "多路选择器"
inputs = ["sel", "a", "b"]
outputs = ["out"]
sequential = false

[dff]
description = "带使能的 D 触发器"
inputs = ["we", "d"]
outputs = ["q"]
sequential = true

[add]
description = "加法器"
inputs = ["a", "b", "cin"]
outputs = ["sum", "cout"]
sequential = false

[not]
description = "非门"
inputs = ["a"]
outputs = ["out"]
sequential = false

[and]
description = "与门"
inputs = ["a", "b"]
outputs = ["out"]
sequential = false

[xor]
description = "异或门"
inputs = ["a", "b"]
outputs = ["out"]
sequential = false

[xnor]
description = "同或门"
inputs = ["a", "b"]
outputs = ["out"]
sequential = false

[or]
description = "或门"
inputs = ["a", "b"]
outputs = ["out"]
sequential = false

[nand]
description = "与非门"
inputs = ["a", "b"]
outputs = ["out"]
sequential = false

[nor]
description = "或非门"
inputs = ["a", "b"]
outputs = ["out"]
sequential = false

[lsl]
description = "逻辑左移器"
inputs = ["a", "offset"]
outputs = ["out"]
sequential = false

[lsr]
description = "逻辑右移器"
inputs = ["a", "offset"]
outputs = ["out"]
sequential = false

[asr]
description = "算术右移器"
inputs = ["a", "offset"]
outputs = ["out"]
sequential = false

[eq]
description = "判等器"
inputs = ["a", "b"]
outputs = ["out"]
sequential = false

[ult]
description = "无符号小于器"
inputs = ["a", "b"]
outputs = ["out"]
sequential = false

[slt]
description = "有符号小于器"
inputs = ["a", "b"]
outputs = ["out"]
sequential = false

[dec]
description = "N-2^N 译码器"
inputs = ["in"]
outputs = ["out"]
sequential = false
